document.getElementById("ls").addEventListener("click",function(){
	window.location="registration.html";
});
document.getElementById('grocery').addEventListener('click',function(){
	window.location="grocery.html";
});
document.getElementById('electronic').addEventListener('click',function(){
	window.location="electronic.html";
});
document.getElementById('textile').addEventListener('click',function(){
	window.location="textile.html";
});
document.getElementById('hp').addEventListener('click',function(){
	window.location="homeproducts.html";
});
